import { useState } from 'react'
import NavBar from './NavBar'
import Footer from './Footer'
import Body from './Body'


function App() {
  const [city, setCity] = useState(cityJson)

  window.addEventListener('keydown', (e) => {
    if (e.key === 'down') {
      console.log('down');
    }
  })

  return (
    <>
      <NavBar setCity={setCity} />
      <Body city={city} />
      <Footer />
    </>
  )
}
export default App

const cityJson = {
  "location": {
    "name": "London",
    "region": "City of London, Greater London",
    "country": "United Kingdom",
    "lat": 51.52,
    "lon": -0.11,
    "tz_id": "Europe/London",
    "localtime_epoch": 1685216315,
    "localtime": "2023-05-27 20:38"
  },
  "current": {
    "last_updated_epoch": 1685215800,
    "last_updated": "2023-05-27 20:30",
    "temp_c": 18,
    "temp_f": 64.4,
    "is_day": 1,
    "condition": {
      "text": "Sunny",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
      "code": 1000
    },
    "wind_mph": 8.1,
    "wind_kph": 13,
    "wind_degree": 110,
    "wind_dir": "ESE",
    "pressure_mb": 1023,
    "pressure_in": 30.21,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 56,
    "cloud": 0,
    "feelslike_c": 18,
    "feelslike_f": 64.4,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 4,
    "gust_mph": 7.6,
    "gust_kph": 12.2
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-05-27",
        "date_epoch": 1685145600,
        "day": {
          "maxtemp_c": 21.4,
          "maxtemp_f": 70.5,
          "mintemp_c": 7.8,
          "mintemp_f": 46,
          "avgtemp_c": 14.6,
          "avgtemp_f": 58.3,
          "maxwind_mph": 8.7,
          "maxwind_kph": 14,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 63,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "04:54 AM",
          "sunset": "09:02 PM",
          "moonrise": "11:58 AM",
          "moonset": "02:19 AM",
          "moon_phase": "First Quarter",
          "moon_illumination": "44",
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1685142000,
            "time": "2023-05-27 00:00",
            "temp_c": 9,
            "temp_f": 48.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 62,
            "wind_dir": "ENE",
            "pressure_mb": 1031,
            "pressure_in": 30.43,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 23,
            "feelslike_c": 7.1,
            "feelslike_f": 44.8,
            "windchill_c": 7.1,
            "windchill_f": 44.8,
            "heatindex_c": 9,
            "heatindex_f": 48.2,
            "dewpoint_c": 7,
            "dewpoint_f": 44.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 1
          },
          {
            "time_epoch": 1685145600,
            "time": "2023-05-27 01:00",
            "temp_c": 8.7,
            "temp_f": 47.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 59,
            "wind_dir": "ENE",
            "pressure_mb": 1030,
            "pressure_in": 30.42,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 17,
            "feelslike_c": 6.9,
            "feelslike_f": 44.4,
            "windchill_c": 6.9,
            "windchill_f": 44.4,
            "heatindex_c": 8.7,
            "heatindex_f": 47.7,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1685149200,
            "time": "2023-05-27 02:00",
            "temp_c": 8.4,
            "temp_f": 47.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 57,
            "wind_dir": "ENE",
            "pressure_mb": 1030,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 16,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 8.4,
            "heatindex_f": 47.1,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1685152800,
            "time": "2023-05-27 03:00",
            "temp_c": 8.1,
            "temp_f": 46.6,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 54,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.39,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 27,
            "feelslike_c": 6.3,
            "feelslike_f": 43.3,
            "windchill_c": 6.3,
            "windchill_f": 43.3,
            "heatindex_c": 8.1,
            "heatindex_f": 46.6,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11,
            "gust_kph": 17.6,
            "uv": 1
          },
          {
            "time_epoch": 1685156400,
            "time": "2023-05-27 04:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 50,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 91,
            "cloud": 40,
            "feelslike_c": 6,
            "feelslike_f": 42.8,
            "windchill_c": 6,
            "windchill_f": 42.8,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1685160000,
            "time": "2023-05-27 05:00",
            "temp_c": 8.4,
            "temp_f": 47.1,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 49,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 37,
            "feelslike_c": 6.8,
            "feelslike_f": 44.2,
            "windchill_c": 6.8,
            "windchill_f": 44.2,
            "heatindex_c": 8.4,
            "heatindex_f": 47.1,
            "dewpoint_c": 6.6,
            "dewpoint_f": 43.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 3
          },
          {
            "time_epoch": 1685163600,
            "time": "2023-05-27 06:00",
            "temp_c": 10,
            "temp_f": 50,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 57,
            "wind_dir": "ENE",
            "pressure_mb": 1029,
            "pressure_in": 30.37,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 13,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10,
            "heatindex_f": 50,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 4
          },
          {
            "time_epoch": 1685167200,
            "time": "2023-05-27 07:00",
            "temp_c": 12,
            "temp_f": 53.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1028,
            "pressure_in": 30.36,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 70,
            "cloud": 3,
            "feelslike_c": 10.6,
            "feelslike_f": 51.1,
            "windchill_c": 10.6,
            "windchill_f": 51.1,
            "heatindex_c": 12,
            "heatindex_f": 53.6,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 4
          },
          {
            "time_epoch": 1685170800,
            "time": "2023-05-27 08:00",
            "temp_c": 13.8,
            "temp_f": 56.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1028,
            "pressure_in": 30.35,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 4,
            "feelslike_c": 12.7,
            "feelslike_f": 54.9,
            "windchill_c": 12.7,
            "windchill_f": 54.9,
            "heatindex_c": 13.8,
            "heatindex_f": 56.8,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 4
          },
          {
            "time_epoch": 1685174400,
            "time": "2023-05-27 09:00",
            "temp_c": 15.5,
            "temp_f": 59.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1027,
            "pressure_in": 30.34,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 5,
            "feelslike_c": 15.5,
            "feelslike_f": 59.9,
            "windchill_c": 15.5,
            "windchill_f": 59.9,
            "heatindex_c": 15.5,
            "heatindex_f": 59.9,
            "dewpoint_c": 5,
            "dewpoint_f": 41,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 5
          },
          {
            "time_epoch": 1685178000,
            "time": "2023-05-27 10:00",
            "temp_c": 17.1,
            "temp_f": 62.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1027,
            "pressure_in": 30.32,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 5,
            "feelslike_c": 17.1,
            "feelslike_f": 62.8,
            "windchill_c": 17.1,
            "windchill_f": 62.8,
            "heatindex_c": 17.1,
            "heatindex_f": 62.8,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 5
          },
          {
            "time_epoch": 1685181600,
            "time": "2023-05-27 11:00",
            "temp_c": 19.4,
            "temp_f": 66.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 65,
            "wind_dir": "ENE",
            "pressure_mb": 1026,
            "pressure_in": 30.31,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 38,
            "cloud": 5,
            "feelslike_c": 19.4,
            "feelslike_f": 66.9,
            "windchill_c": 19.4,
            "windchill_f": 66.9,
            "heatindex_c": 19.4,
            "heatindex_f": 66.9,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 5
          },
          {
            "time_epoch": 1685185200,
            "time": "2023-05-27 12:00",
            "temp_c": 20.6,
            "temp_f": 69.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 64,
            "wind_dir": "ENE",
            "pressure_mb": 1026,
            "pressure_in": 30.29,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 35,
            "cloud": 5,
            "feelslike_c": 20.6,
            "feelslike_f": 69.1,
            "windchill_c": 20.6,
            "windchill_f": 69.1,
            "heatindex_c": 20.6,
            "heatindex_f": 69.1,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 6
          },
          {
            "time_epoch": 1685188800,
            "time": "2023-05-27 13:00",
            "temp_c": 21.2,
            "temp_f": 70.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 65,
            "wind_dir": "ENE",
            "pressure_mb": 1025,
            "pressure_in": 30.27,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 34,
            "cloud": 6,
            "feelslike_c": 21.2,
            "feelslike_f": 70.2,
            "windchill_c": 21.2,
            "windchill_f": 70.2,
            "heatindex_c": 23.4,
            "heatindex_f": 74.1,
            "dewpoint_c": 4.9,
            "dewpoint_f": 40.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 6
          },
          {
            "time_epoch": 1685192400,
            "time": "2023-05-27 14:00",
            "temp_c": 21.5,
            "temp_f": 70.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1025,
            "pressure_in": 30.26,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 35,
            "cloud": 6,
            "feelslike_c": 21.5,
            "feelslike_f": 70.7,
            "windchill_c": 21.5,
            "windchill_f": 70.7,
            "heatindex_c": 23.6,
            "heatindex_f": 74.5,
            "dewpoint_c": 5.3,
            "dewpoint_f": 41.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 6
          },
          {
            "time_epoch": 1685196000,
            "time": "2023-05-27 15:00",
            "temp_c": 21.7,
            "temp_f": 71.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 64,
            "wind_dir": "ENE",
            "pressure_mb": 1024,
            "pressure_in": 30.25,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 36,
            "cloud": 6,
            "feelslike_c": 21.7,
            "feelslike_f": 71.1,
            "windchill_c": 21.7,
            "windchill_f": 71.1,
            "heatindex_c": 23.7,
            "heatindex_f": 74.7,
            "dewpoint_c": 6.1,
            "dewpoint_f": 43,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 6
          },
          {
            "time_epoch": 1685199600,
            "time": "2023-05-27 16:00",
            "temp_c": 21.4,
            "temp_f": 70.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1024,
            "pressure_in": 30.25,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 39,
            "cloud": 6,
            "feelslike_c": 21.4,
            "feelslike_f": 70.5,
            "windchill_c": 21.4,
            "windchill_f": 70.5,
            "heatindex_c": 23.8,
            "heatindex_f": 74.8,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 6
          },
          {
            "time_epoch": 1685203200,
            "time": "2023-05-27 17:00",
            "temp_c": 20.7,
            "temp_f": 69.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 8,
            "feelslike_c": 20.7,
            "feelslike_f": 69.3,
            "windchill_c": 20.7,
            "windchill_f": 69.3,
            "heatindex_c": 20.7,
            "heatindex_f": 69.3,
            "dewpoint_c": 7.9,
            "dewpoint_f": 46.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 6
          },
          {
            "time_epoch": 1685206800,
            "time": "2023-05-27 18:00",
            "temp_c": 19.8,
            "temp_f": 67.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 7,
            "feelslike_c": 19.8,
            "feelslike_f": 67.6,
            "windchill_c": 19.8,
            "windchill_f": 67.6,
            "heatindex_c": 19.8,
            "heatindex_f": 67.6,
            "dewpoint_c": 9.2,
            "dewpoint_f": 48.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.7,
            "gust_kph": 14,
            "uv": 5
          },
          {
            "time_epoch": 1685210400,
            "time": "2023-05-27 19:00",
            "temp_c": 18.5,
            "temp_f": 65.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 82,
            "wind_dir": "E",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 58,
            "cloud": 8,
            "feelslike_c": 18.5,
            "feelslike_f": 65.3,
            "windchill_c": 18.5,
            "windchill_f": 65.3,
            "heatindex_c": 18.5,
            "heatindex_f": 65.3,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 5
          },
          {
            "time_epoch": 1685214000,
            "time": "2023-05-27 20:00",
            "temp_c": 14.1,
            "temp_f": 57.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 91,
            "wind_dir": "E",
            "pressure_mb": 1025,
            "pressure_in": 30.25,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 7,
            "feelslike_c": 13.8,
            "feelslike_f": 56.8,
            "windchill_c": 13.8,
            "windchill_f": 56.8,
            "heatindex_c": 14.1,
            "heatindex_f": 57.4,
            "dewpoint_c": 8,
            "dewpoint_f": 46.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.6,
            "gust_kph": 12.2,
            "uv": 4
          },
          {
            "time_epoch": 1685217600,
            "time": "2023-05-27 21:00",
            "temp_c": 12.9,
            "temp_f": 55.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 84,
            "wind_dir": "E",
            "pressure_mb": 1025,
            "pressure_in": 30.26,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 5,
            "feelslike_c": 12.7,
            "feelslike_f": 54.9,
            "windchill_c": 12.7,
            "windchill_f": 54.9,
            "heatindex_c": 12.9,
            "heatindex_f": 55.2,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.5,
            "gust_kph": 10.4,
            "uv": 4
          },
          {
            "time_epoch": 1685221200,
            "time": "2023-05-27 22:00",
            "temp_c": 12.2,
            "temp_f": 54,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 70,
            "wind_dir": "ENE",
            "pressure_mb": 1025,
            "pressure_in": 30.26,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 4,
            "feelslike_c": 12.1,
            "feelslike_f": 53.8,
            "windchill_c": 12.1,
            "windchill_f": 53.8,
            "heatindex_c": 12.2,
            "heatindex_f": 54,
            "dewpoint_c": 7.6,
            "dewpoint_f": 45.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 1
          },
          {
            "time_epoch": 1685224800,
            "time": "2023-05-27 23:00",
            "temp_c": 11.8,
            "temp_f": 53.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1025,
            "pressure_in": 30.25,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 3,
            "feelslike_c": 11.7,
            "feelslike_f": 53.1,
            "windchill_c": 11.7,
            "windchill_f": 53.1,
            "heatindex_c": 11.8,
            "heatindex_f": 53.2,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          }
        ]
      },
      {
        "date": "2023-05-28",
        "date_epoch": 1685232000,
        "day": {
          "maxtemp_c": 20.7,
          "maxtemp_f": 69.3,
          "mintemp_c": 9.4,
          "mintemp_f": 48.9,
          "avgtemp_c": 14.6,
          "avgtemp_f": 58.3,
          "maxwind_mph": 12.5,
          "maxwind_kph": 20.2,
          "totalprecip_mm": 0.3,
          "totalprecip_in": 0.01,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 64,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 77,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 3
        },
        "astro": {
          "sunrise": "04:53 AM",
          "sunset": "09:03 PM",
          "moonrise": "01:10 PM",
          "moonset": "02:33 AM",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": "53",
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1685228400,
            "time": "2023-05-28 00:00",
            "temp_c": 10.8,
            "temp_f": 51.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 59,
            "wind_dir": "ENE",
            "pressure_mb": 1024,
            "pressure_in": 30.25,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 3,
            "feelslike_c": 10.7,
            "feelslike_f": 51.3,
            "windchill_c": 10.7,
            "windchill_f": 51.3,
            "heatindex_c": 10.8,
            "heatindex_f": 51.4,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1685232000,
            "time": "2023-05-28 01:00",
            "temp_c": 10.4,
            "temp_f": 50.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 42,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 8,
            "feelslike_c": 10.1,
            "feelslike_f": 50.2,
            "windchill_c": 10.1,
            "windchill_f": 50.2,
            "heatindex_c": 10.4,
            "heatindex_f": 50.7,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.3,
            "gust_kph": 10.1,
            "uv": 1
          },
          {
            "time_epoch": 1685235600,
            "time": "2023-05-28 02:00",
            "temp_c": 10.2,
            "temp_f": 50.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 38,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 7,
            "feelslike_c": 9.9,
            "feelslike_f": 49.8,
            "windchill_c": 9.9,
            "windchill_f": 49.8,
            "heatindex_c": 10.2,
            "heatindex_f": 50.4,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.3,
            "gust_kph": 10.1,
            "uv": 1
          },
          {
            "time_epoch": 1685239200,
            "time": "2023-05-28 03:00",
            "temp_c": 10,
            "temp_f": 50,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 30,
            "wind_dir": "NNE",
            "pressure_mb": 1023,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 4,
            "feelslike_c": 9.5,
            "feelslike_f": 49.1,
            "windchill_c": 9.5,
            "windchill_f": 49.1,
            "heatindex_c": 10,
            "heatindex_f": 50,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 1
          },
          {
            "time_epoch": 1685242800,
            "time": "2023-05-28 04:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 36,
            "wind_dir": "NE",
            "pressure_mb": 1023,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 3,
            "feelslike_c": 8.8,
            "feelslike_f": 47.8,
            "windchill_c": 8.8,
            "windchill_f": 47.8,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.9,
            "gust_kph": 11.2,
            "uv": 1
          },
          {
            "time_epoch": 1685246400,
            "time": "2023-05-28 05:00",
            "temp_c": 10.1,
            "temp_f": 50.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 31,
            "wind_dir": "NNE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 3,
            "feelslike_c": 9.6,
            "feelslike_f": 49.3,
            "windchill_c": 9.6,
            "windchill_f": 49.3,
            "heatindex_c": 10.1,
            "heatindex_f": 50.2,
            "dewpoint_c": 5.7,
            "dewpoint_f": 42.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 4
          },
          {
            "time_epoch": 1685250000,
            "time": "2023-05-28 06:00",
            "temp_c": 11.9,
            "temp_f": 53.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 38,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 4,
            "feelslike_c": 11.1,
            "feelslike_f": 52,
            "windchill_c": 11.1,
            "windchill_f": 52,
            "heatindex_c": 11.9,
            "heatindex_f": 53.4,
            "dewpoint_c": 4.8,
            "dewpoint_f": 40.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 4
          },
          {
            "time_epoch": 1685253600,
            "time": "2023-05-28 07:00",
            "temp_c": 14,
            "temp_f": 57.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 44,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 47,
            "cloud": 7,
            "feelslike_c": 13.3,
            "feelslike_f": 55.9,
            "windchill_c": 13.3,
            "windchill_f": 55.9,
            "heatindex_c": 14,
            "heatindex_f": 57.2,
            "dewpoint_c": 2.8,
            "dewpoint_f": 37,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 4
          },
          {
            "time_epoch": 1685257200,
            "time": "2023-05-28 08:00",
            "temp_c": 16,
            "temp_f": 60.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 46,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 37,
            "cloud": 15,
            "feelslike_c": 16,
            "feelslike_f": 60.8,
            "windchill_c": 16,
            "windchill_f": 60.8,
            "heatindex_c": 16,
            "heatindex_f": 60.8,
            "dewpoint_c": 1.5,
            "dewpoint_f": 34.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 5
          },
          {
            "time_epoch": 1685260800,
            "time": "2023-05-28 09:00",
            "temp_c": 17.7,
            "temp_f": 63.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 50,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 35,
            "cloud": 20,
            "feelslike_c": 17.7,
            "feelslike_f": 63.9,
            "windchill_c": 17.7,
            "windchill_f": 63.9,
            "heatindex_c": 17.7,
            "heatindex_f": 63.9,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 5
          },
          {
            "time_epoch": 1685264400,
            "time": "2023-05-28 10:00",
            "temp_c": 18.8,
            "temp_f": 65.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 51,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 38,
            "cloud": 13,
            "feelslike_c": 18.8,
            "feelslike_f": 65.8,
            "windchill_c": 18.8,
            "windchill_f": 65.8,
            "heatindex_c": 18.8,
            "heatindex_f": 65.8,
            "dewpoint_c": 4.1,
            "dewpoint_f": 39.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 5
          },
          {
            "time_epoch": 1685268000,
            "time": "2023-05-28 11:00",
            "temp_c": 20.5,
            "temp_f": 68.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 54,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 6,
            "feelslike_c": 20.5,
            "feelslike_f": 68.9,
            "windchill_c": 20.5,
            "windchill_f": 68.9,
            "heatindex_c": 20.5,
            "heatindex_f": 68.9,
            "dewpoint_c": 7.6,
            "dewpoint_f": 45.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.8,
            "uv": 6
          },
          {
            "time_epoch": 1685271600,
            "time": "2023-05-28 12:00",
            "temp_c": 20.8,
            "temp_f": 69.4,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 55,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 34,
            "feelslike_c": 20.8,
            "feelslike_f": 69.4,
            "windchill_c": 20.8,
            "windchill_f": 69.4,
            "heatindex_c": 20.8,
            "heatindex_f": 69.4,
            "dewpoint_c": 8.9,
            "dewpoint_f": 48,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13,
            "gust_kph": 20.9,
            "uv": 6
          },
          {
            "time_epoch": 1685275200,
            "time": "2023-05-28 13:00",
            "temp_c": 21.2,
            "temp_f": 70.2,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 58,
            "wind_dir": "ENE",
            "pressure_mb": 1024,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 47,
            "cloud": 74,
            "feelslike_c": 21.2,
            "feelslike_f": 70.2,
            "windchill_c": 21.2,
            "windchill_f": 70.2,
            "heatindex_c": 24.2,
            "heatindex_f": 75.6,
            "dewpoint_c": 9.5,
            "dewpoint_f": 49.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 5
          },
          {
            "time_epoch": 1685278800,
            "time": "2023-05-28 14:00",
            "temp_c": 20.7,
            "temp_f": 69.3,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 58,
            "wind_dir": "ENE",
            "pressure_mb": 1023,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 86,
            "feelslike_c": 20.7,
            "feelslike_f": 69.3,
            "windchill_c": 20.7,
            "windchill_f": 69.3,
            "heatindex_c": 20.7,
            "heatindex_f": 69.3,
            "dewpoint_c": 9.9,
            "dewpoint_f": 49.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.6,
            "gust_kph": 22,
            "uv": 5
          },
          {
            "time_epoch": 1685282400,
            "time": "2023-05-28 15:00",
            "temp_c": 19.7,
            "temp_f": 67.5,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 54,
            "wind_dir": "NE",
            "pressure_mb": 1023,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 54,
            "cloud": 84,
            "feelslike_c": 19.7,
            "feelslike_f": 67.5,
            "windchill_c": 19.7,
            "windchill_f": 67.5,
            "heatindex_c": 19.7,
            "heatindex_f": 67.5,
            "dewpoint_c": 10,
            "dewpoint_f": 50,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13,
            "gust_kph": 20.9,
            "uv": 4
          },
          {
            "time_epoch": 1685286000,
            "time": "2023-05-28 16:00",
            "temp_c": 19.3,
            "temp_f": 66.7,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 54,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 86,
            "feelslike_c": 19.3,
            "feelslike_f": 66.7,
            "windchill_c": 19.3,
            "windchill_f": 66.7,
            "heatindex_c": 19.3,
            "heatindex_f": 66.7,
            "dewpoint_c": 10.5,
            "dewpoint_f": 50.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 4
          },
          {
            "time_epoch": 1685289600,
            "time": "2023-05-28 17:00",
            "temp_c": 18.3,
            "temp_f": 64.9,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 48,
            "wind_dir": "NE",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 78,
            "feelslike_c": 18.3,
            "feelslike_f": 64.9,
            "windchill_c": 18.3,
            "windchill_f": 64.9,
            "heatindex_c": 18.3,
            "heatindex_f": 64.9,
            "dewpoint_c": 11.1,
            "dewpoint_f": 52,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 4
          },
          {
            "time_epoch": 1685293200,
            "time": "2023-05-28 18:00",
            "temp_c": 17.6,
            "temp_f": 63.7,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 45,
            "wind_dir": "NE",
            "pressure_mb": 1025,
            "pressure_in": 30.25,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 68,
            "cloud": 65,
            "feelslike_c": 17.6,
            "feelslike_f": 63.7,
            "windchill_c": 17.6,
            "windchill_f": 63.7,
            "heatindex_c": 17.6,
            "heatindex_f": 63.7,
            "dewpoint_c": 11.6,
            "dewpoint_f": 52.9,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 4
          },
          {
            "time_epoch": 1685296800,
            "time": "2023-05-28 19:00",
            "temp_c": 16,
            "temp_f": 60.8,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 48,
            "wind_dir": "NE",
            "pressure_mb": 1025,
            "pressure_in": 30.27,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 81,
            "feelslike_c": 16,
            "feelslike_f": 60.8,
            "windchill_c": 16,
            "windchill_f": 60.8,
            "heatindex_c": 16,
            "heatindex_f": 60.8,
            "dewpoint_c": 11.7,
            "dewpoint_f": 53.1,
            "will_it_rain": 1,
            "chance_of_rain": 73,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 4
          },
          {
            "time_epoch": 1685300400,
            "time": "2023-05-28 20:00",
            "temp_c": 13.7,
            "temp_f": 56.7,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 48,
            "wind_dir": "NE",
            "pressure_mb": 1026,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 79,
            "feelslike_c": 12,
            "feelslike_f": 53.6,
            "windchill_c": 12,
            "windchill_f": 53.6,
            "heatindex_c": 13.7,
            "heatindex_f": 56.7,
            "dewpoint_c": 10.4,
            "dewpoint_f": 50.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.8,
            "gust_kph": 27,
            "uv": 3
          },
          {
            "time_epoch": 1685304000,
            "time": "2023-05-28 21:00",
            "temp_c": 12.2,
            "temp_f": 54,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1027,
            "pressure_in": 30.32,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 80,
            "feelslike_c": 10.2,
            "feelslike_f": 50.4,
            "windchill_c": 10.2,
            "windchill_f": 50.4,
            "heatindex_c": 12.2,
            "heatindex_f": 54,
            "dewpoint_c": 9,
            "dewpoint_f": 48.2,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 3
          },
          {
            "time_epoch": 1685307600,
            "time": "2023-05-28 22:00",
            "temp_c": 11.1,
            "temp_f": 52,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1027,
            "pressure_in": 30.32,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 11,
            "feelslike_c": 8.9,
            "feelslike_f": 48,
            "windchill_c": 8.9,
            "windchill_f": 48,
            "heatindex_c": 11.1,
            "heatindex_f": 52,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 1
          },
          {
            "time_epoch": 1685311200,
            "time": "2023-05-28 23:00",
            "temp_c": 10.2,
            "temp_f": 50.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 42,
            "wind_dir": "NE",
            "pressure_mb": 1027,
            "pressure_in": 30.34,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 13,
            "feelslike_c": 8,
            "feelslike_f": 46.4,
            "windchill_c": 8,
            "windchill_f": 46.4,
            "heatindex_c": 10.2,
            "heatindex_f": 50.4,
            "dewpoint_c": 7.1,
            "dewpoint_f": 44.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 1
          }
        ]
      },
      {
        "date": "2023-05-29",
        "date_epoch": 1685318400,
        "day": {
          "maxtemp_c": 18.4,
          "maxtemp_f": 65.1,
          "mintemp_c": 7.4,
          "mintemp_f": 45.3,
          "avgtemp_c": 12.7,
          "avgtemp_f": 54.8,
          "maxwind_mph": 13.4,
          "maxwind_kph": 21.6,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 64,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "04:52 AM",
          "sunset": "09:05 PM",
          "moonrise": "02:21 PM",
          "moonset": "02:44 AM",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": "63",
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1685314800,
            "time": "2023-05-29 00:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 39,
            "wind_dir": "NE",
            "pressure_mb": 1028,
            "pressure_in": 30.34,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 78,
            "feelslike_c": 7.1,
            "feelslike_f": 44.8,
            "windchill_c": 7.1,
            "windchill_f": 44.8,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44.1,
            "will_it_rain": 0,
            "chance_of_rain": 62,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.6,
            "gust_kph": 22,
            "uv": 1
          },
          {
            "time_epoch": 1685318400,
            "time": "2023-05-29 01:00",
            "temp_c": 8.8,
            "temp_f": 47.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 36,
            "wind_dir": "NE",
            "pressure_mb": 1028,
            "pressure_in": 30.35,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 23,
            "feelslike_c": 6.2,
            "feelslike_f": 43.2,
            "windchill_c": 6.2,
            "windchill_f": 43.2,
            "heatindex_c": 8.8,
            "heatindex_f": 47.8,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 1
          },
          {
            "time_epoch": 1685322000,
            "time": "2023-05-29 02:00",
            "temp_c": 8.4,
            "temp_f": 47.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1028,
            "pressure_in": 30.35,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 20,
            "feelslike_c": 5.9,
            "feelslike_f": 42.6,
            "windchill_c": 5.9,
            "windchill_f": 42.6,
            "heatindex_c": 8.4,
            "heatindex_f": 47.1,
            "dewpoint_c": 6,
            "dewpoint_f": 42.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 1
          },
          {
            "time_epoch": 1685325600,
            "time": "2023-05-29 03:00",
            "temp_c": 8.1,
            "temp_f": 46.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 35,
            "wind_dir": "NE",
            "pressure_mb": 1028,
            "pressure_in": 30.36,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 23,
            "feelslike_c": 5.6,
            "feelslike_f": 42.1,
            "windchill_c": 5.6,
            "windchill_f": 42.1,
            "heatindex_c": 8.1,
            "heatindex_f": 46.6,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 1
          },
          {
            "time_epoch": 1685329200,
            "time": "2023-05-29 04:00",
            "temp_c": 7.7,
            "temp_f": 45.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 37,
            "wind_dir": "NE",
            "pressure_mb": 1028,
            "pressure_in": 30.36,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 23,
            "feelslike_c": 5.1,
            "feelslike_f": 41.2,
            "windchill_c": 5.1,
            "windchill_f": 41.2,
            "heatindex_c": 7.7,
            "heatindex_f": 45.9,
            "dewpoint_c": 5.6,
            "dewpoint_f": 42.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.6,
            "gust_kph": 22,
            "uv": 1
          },
          {
            "time_epoch": 1685332800,
            "time": "2023-05-29 05:00",
            "temp_c": 8.1,
            "temp_f": 46.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 39,
            "wind_dir": "NE",
            "pressure_mb": 1028,
            "pressure_in": 30.37,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 13,
            "feelslike_c": 5.6,
            "feelslike_f": 42.1,
            "windchill_c": 5.6,
            "windchill_f": 42.1,
            "heatindex_c": 8.1,
            "heatindex_f": 46.6,
            "dewpoint_c": 5.4,
            "dewpoint_f": 41.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13,
            "gust_kph": 20.9,
            "uv": 3
          },
          {
            "time_epoch": 1685336400,
            "time": "2023-05-29 06:00",
            "temp_c": 9.3,
            "temp_f": 48.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 2,
            "feelslike_c": 6.7,
            "feelslike_f": 44.1,
            "windchill_c": 6.7,
            "windchill_f": 44.1,
            "heatindex_c": 9.3,
            "heatindex_f": 48.7,
            "dewpoint_c": 5.2,
            "dewpoint_f": 41.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 3
          },
          {
            "time_epoch": 1685340000,
            "time": "2023-05-29 07:00",
            "temp_c": 10.9,
            "temp_f": 51.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 47,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 17,
            "feelslike_c": 8.5,
            "feelslike_f": 47.3,
            "windchill_c": 8.5,
            "windchill_f": 47.3,
            "heatindex_c": 10.9,
            "heatindex_f": 51.6,
            "dewpoint_c": 5.1,
            "dewpoint_f": 41.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.1,
            "gust_kph": 22.7,
            "uv": 4
          },
          {
            "time_epoch": 1685343600,
            "time": "2023-05-29 08:00",
            "temp_c": 12.1,
            "temp_f": 53.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 49,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.39,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 61,
            "cloud": 18,
            "feelslike_c": 10,
            "feelslike_f": 50,
            "windchill_c": 10,
            "windchill_f": 50,
            "heatindex_c": 12.1,
            "heatindex_f": 53.8,
            "dewpoint_c": 4.8,
            "dewpoint_f": 40.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 4
          },
          {
            "time_epoch": 1685347200,
            "time": "2023-05-29 09:00",
            "temp_c": 13.6,
            "temp_f": 56.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 49,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 55,
            "cloud": 16,
            "feelslike_c": 12,
            "feelslike_f": 53.6,
            "windchill_c": 12,
            "windchill_f": 53.6,
            "heatindex_c": 13.6,
            "heatindex_f": 56.5,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 4
          },
          {
            "time_epoch": 1685350800,
            "time": "2023-05-29 10:00",
            "temp_c": 15,
            "temp_f": 59,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 49,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 20,
            "feelslike_c": 13.7,
            "feelslike_f": 56.7,
            "windchill_c": 13.7,
            "windchill_f": 56.7,
            "heatindex_c": 15,
            "heatindex_f": 59,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 5
          },
          {
            "time_epoch": 1685354400,
            "time": "2023-05-29 11:00",
            "temp_c": 16.5,
            "temp_f": 61.7,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 50,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 47,
            "cloud": 33,
            "feelslike_c": 16.5,
            "feelslike_f": 61.7,
            "windchill_c": 16.5,
            "windchill_f": 61.7,
            "heatindex_c": 16.5,
            "heatindex_f": 61.7,
            "dewpoint_c": 5,
            "dewpoint_f": 41,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 5
          },
          {
            "time_epoch": 1685358000,
            "time": "2023-05-29 12:00",
            "temp_c": 17.2,
            "temp_f": 63,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 54,
            "wind_dir": "NE",
            "pressure_mb": 1028,
            "pressure_in": 30.37,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 90,
            "feelslike_c": 17.2,
            "feelslike_f": 63,
            "windchill_c": 17.2,
            "windchill_f": 63,
            "heatindex_c": 17.2,
            "heatindex_f": 63,
            "dewpoint_c": 5,
            "dewpoint_f": 41,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 4
          },
          {
            "time_epoch": 1685361600,
            "time": "2023-05-29 13:00",
            "temp_c": 17.5,
            "temp_f": 63.5,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 57,
            "wind_dir": "ENE",
            "pressure_mb": 1028,
            "pressure_in": 30.37,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 97,
            "feelslike_c": 17.5,
            "feelslike_f": 63.5,
            "windchill_c": 17.5,
            "windchill_f": 63.5,
            "heatindex_c": 17.5,
            "heatindex_f": 63.5,
            "dewpoint_c": 5.3,
            "dewpoint_f": 41.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 4
          },
          {
            "time_epoch": 1685365200,
            "time": "2023-05-29 14:00",
            "temp_c": 18.1,
            "temp_f": 64.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 58,
            "wind_dir": "ENE",
            "pressure_mb": 1028,
            "pressure_in": 30.36,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 7,
            "feelslike_c": 18.1,
            "feelslike_f": 64.6,
            "windchill_c": 18.1,
            "windchill_f": 64.6,
            "heatindex_c": 18.1,
            "heatindex_f": 64.6,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 5
          },
          {
            "time_epoch": 1685368800,
            "time": "2023-05-29 15:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 57,
            "wind_dir": "ENE",
            "pressure_mb": 1028,
            "pressure_in": 30.36,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 13,
            "feelslike_c": 17.9,
            "feelslike_f": 64.2,
            "windchill_c": 17.9,
            "windchill_f": 64.2,
            "heatindex_c": 17.9,
            "heatindex_f": 64.2,
            "dewpoint_c": 5.4,
            "dewpoint_f": 41.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.4,
            "gust_kph": 24.8,
            "uv": 5
          },
          {
            "time_epoch": 1685372400,
            "time": "2023-05-29 16:00",
            "temp_c": 17.5,
            "temp_f": 63.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 55,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.37,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 12,
            "feelslike_c": 17.5,
            "feelslike_f": 63.5,
            "windchill_c": 17.5,
            "windchill_f": 63.5,
            "heatindex_c": 17.5,
            "heatindex_f": 63.5,
            "dewpoint_c": 4.8,
            "dewpoint_f": 40.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 5
          },
          {
            "time_epoch": 1685376000,
            "time": "2023-05-29 17:00",
            "temp_c": 16.8,
            "temp_f": 62.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 53,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.38,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 9,
            "feelslike_c": 16.8,
            "feelslike_f": 62.2,
            "windchill_c": 16.8,
            "windchill_f": 62.2,
            "heatindex_c": 16.8,
            "heatindex_f": 62.2,
            "dewpoint_c": 5.2,
            "dewpoint_f": 41.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 5
          },
          {
            "time_epoch": 1685379600,
            "time": "2023-05-29 18:00",
            "temp_c": 16.1,
            "temp_f": 61,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 51,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.39,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 5,
            "feelslike_c": 16.1,
            "feelslike_f": 61,
            "windchill_c": 16.1,
            "windchill_f": 61,
            "heatindex_c": 16.1,
            "heatindex_f": 61,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 5
          },
          {
            "time_epoch": 1685383200,
            "time": "2023-05-29 19:00",
            "temp_c": 15,
            "temp_f": 59,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 48,
            "wind_dir": "NE",
            "pressure_mb": 1029,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 5,
            "feelslike_c": 13.8,
            "feelslike_f": 56.8,
            "windchill_c": 13.8,
            "windchill_f": 56.8,
            "heatindex_c": 15,
            "heatindex_f": 59,
            "dewpoint_c": 7,
            "dewpoint_f": 44.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 5
          },
          {
            "time_epoch": 1685386800,
            "time": "2023-05-29 20:00",
            "temp_c": 11.7,
            "temp_f": 53.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 47,
            "wind_dir": "NE",
            "pressure_mb": 1030,
            "pressure_in": 30.41,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 7,
            "feelslike_c": 9.7,
            "feelslike_f": 49.5,
            "windchill_c": 9.7,
            "windchill_f": 49.5,
            "heatindex_c": 11.7,
            "heatindex_f": 53.1,
            "dewpoint_c": 5.6,
            "dewpoint_f": 42.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 4
          },
          {
            "time_epoch": 1685390400,
            "time": "2023-05-29 21:00",
            "temp_c": 10.5,
            "temp_f": 50.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 45,
            "wind_dir": "NE",
            "pressure_mb": 1030,
            "pressure_in": 30.43,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 6,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.5,
            "heatindex_f": 50.9,
            "dewpoint_c": 5.5,
            "dewpoint_f": 41.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 4
          },
          {
            "time_epoch": 1685394000,
            "time": "2023-05-29 22:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1030,
            "pressure_in": 30.43,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 7,
            "feelslike_c": 7.4,
            "feelslike_f": 45.3,
            "windchill_c": 7.4,
            "windchill_f": 45.3,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 5.6,
            "dewpoint_f": 42.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.6,
            "gust_kph": 22,
            "uv": 1
          },
          {
            "time_epoch": 1685397600,
            "time": "2023-05-29 23:00",
            "temp_c": 9.1,
            "temp_f": 48.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1030,
            "pressure_in": 30.42,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 7,
            "feelslike_c": 6.7,
            "feelslike_f": 44.1,
            "windchill_c": 6.7,
            "windchill_f": 44.1,
            "heatindex_c": 9.1,
            "heatindex_f": 48.4,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 1
          }
        ]
      }
    ]
  }
}